/*
 * Copyright 2002-2012 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.yingzhuo.captcha4j.component;

import java.util.Random;

import com.github.yingzhuo.captcha4j.TextProducer;

/**
 * TextProducer Implementation that will return Chinese characters..
 */
public class ChineseTextProducer implements TextProducer {

	private String[] simplifiedChineseTexts = new String[] {
			"百福具臻",
			"福寿康宁",
			"瑞启德门",
			"鸿喜云集",
			"福至心灵",
			"门潭赠庆",
			"恭喜发财",
			"五谷丰登",
			"福齐南山",
			"福寿双全",
			"福寿年高",
			"福惠双修",
			"德门积庆",
			"升祺骈福",
			"潭祉迎祥",
			"福祉骈蕃",
			"五福齐全",
			"三阳开泰",
			"祥瑞福辏",
			"福禄长久",
			"潭祺迪吉",
			"华星凝辉",
			"万寿无疆",
			"百龄眉寿",
			"返老还童",
			"寿如南岳",
			"千岁之桃",
			"松鹤舞凤",
			"美意富贵",
			"麻姑酒满",
			"天保九如",
			"期颐之寿",
			"南山献颂",
			"算衍春龄",
			"福海寿山",
			"荣跻七秩",
			"年登大耋",
			"天伦之乐",
			"鸾凤和鸣",
			"比翼齐飞",
			"珠连璧合",
			"芝兰千载",
			"洞房花烛",
			"秦晋之好",
			"琴瑟永偕",
			"紫气东来",
			"吉星高照",
			"新婚燕尔",
			"乔迁之喜",
			"金玉满堂",
			"日转千阶",
			"鱼跃龙门",
			"甲第星罗",
			"光辉灿烂",
			"登峰造极",
			"富贵荣华",
			"雁塔题名",
			"饮至策勋",
			"云程发韧",
			"纡朱怀金",
			"鱼跃龙门",
			"厚德载物",
			"德隆望重",
			"冰清玉洁",
			"积爱成福",
			"为善最乐",
			"鞠躬尽瘁",
			"至诚高节",
			"尽忠报国",
			"国泰民安",
			"室雅人和",
			"风顺家兴",
			"四海升平",
			"民殷国富",
			"万事如意",
			"风和日暖",
			"和谐社会",
			"竹报平安",
			"读书万卷",
			"励精图志",
			"业精于勤",
			"耕云种月",
			"天道酬勤",
			"开卷有益",
			"学而不厌",
			"闻鸡起舞",
			"胸怀洒落",
			"温恭自虚",
			"慎静尚宽",
			"澄心清神",
			"知足常乐",
			"百忍成金",
			"气若幽兰",
			"豁达大度",
			"怡然自乐",
			"冰壶秋月",
			"一马当先",
			"出类拔萃",
			"同心协力",
			"个中翘楚",
			"无与伦比",
			"超越巅峰",
			"劳苦功高",
			"卓越干练",
			"品资卓越",
			"无懈可击",
			"成绩斐然",
			"绩效斐然",
			"敬业乐群",
			"业绩辉煌",
			"绝伦逸群",
			"勤奋楷模",
			"筚路蓝缕",
			"运筹帷幄",
			"大吉大利",
			"五福临门",
			"四季平安",
			"心想事成",
			"吉祥如意",
			"吉庆有余",
			"年年有余",
			"花开富贵",
			"金玉满堂",
			"竹报平安",
			"招财进宝",
			"满堂富贵",
			"新昭如意",
			"迎春纳福",
			"贺颂春厘",
			"富贵有余",
			"福星高照",
			"开岁百福",
			"事事顺心",
			"添福增寿",
			"恭贺新禧",
			"万事如意",
			"恭喜发财",
			"岁岁平安",
			"英才得展",
			"大展鸿猷",
			"任重道远",
			"步步高升",
			"青云直上",
			"高瞻远瞩",
			"功绩卓著",
			"鹏程万里",
			"丰功伟绩",
			"懋绩可风",
			"名标金榜",
			"才高八斗",
			"才华横溢",
			"名列前芧",
			"名冠群伦",
			"出类拔萃",
			"前程万里",
			"前途辉煌",
			"鹏程万里",
			"云天厚谊",
			"云谊永存",
			"聚情永怀",
			"云天高谊",
			"盟谊永固",
			"情谊永怀",
			"敦睦情谊",
			"惠泽广备",
			"至诚永念",
			"惜别常忆",
			"德业弥珍",
			"锦情义茂"
	};

	/**
	 * @return random Chinese text
	 */
	public String createText() {
		return simplifiedChineseTexts[new Random()
				.nextInt(simplifiedChineseTexts.length)];
	}
}
